//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int id { get; set; }
        public int userID { get; set; }
        public string location { get; set; }
        public double size { get; set; }
        public double price { get; set; }
    }
}
