//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad : BaseModel
    {
        public int id { get; set; }
        public int userID { get; set; }
        public string location { get; set; }
        public double size { get; set; }
        public double price { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as Ad);
        }

        public bool Equals(Ad other)
        {
            return other != null &&
                   this.id == other.id &&
                   this.userID == other.userID &&
                   this.price == other.price &&
                   this.size == other.size &&
                   this.location.Equals(other.location);

        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }
    }
}
