//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_3.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class User : BaseModel
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as User);
        }

        public bool Equals(User other)
        {
            return other != null &&
                   this.id == other.id &&
                   this.username.Equals(other.username) &&
                   this.password.Equals(other.password) &&
                   this.name.Equals(other.name);
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }
    }
}
